version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

  drf:
    image: drf_pytest_swagger:latest
    container_name: drf_pytest_swagger
    tty: true
    restart: on-failure
    build:
      context: .
      network: host
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations && 
        python manage.py migrate && 
        python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db



