version: "3.9"

services:
  drf:
    image: drf_pytest_swagger:latest
    container_name: drf_pytest_swagger
    tty: true
    restart: on-failure
    build:
      context: .
      network: host
    env_file:
      - .env
    ports:
      - "7983:7983"
    command: sh -c "/drf_pytest_swagger/entrypoint.sh"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: psql_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    healthcheck:
      test: ['CMD-SHELL', 'pg-ready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5