# Generated by Django 4.1.5 on 2023-02-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='t_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
